// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SnsSnapshotAchievementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SnsSnapshotAchievement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 発祥
     * </pre>
     *
     * <code>string countryOfOrigin = 2;</code>
     * @return The countryOfOrigin.
     */
    java.lang.String getCountryOfOrigin();
    /**
     * <pre>
     * 発祥
     * </pre>
     *
     * <code>string countryOfOrigin = 2;</code>
     * @return The bytes for countryOfOrigin.
     */
    com.google.protobuf.ByteString
        getCountryOfOriginBytes();

    /**
     * <pre>
     * mau
     * </pre>
     *
     * <code>int64 monthlyActiveUser = 3;</code>
     * @return The monthlyActiveUser.
     */
    long getMonthlyActiveUser();

    /**
     * <pre>
     * average revenue per user
     * </pre>
     *
     * <code>int64 arpu = 4;</code>
     * @return The arpu.
     */
    long getArpu();

    /**
     * <pre>
     * リリース
     * </pre>
     *
     * <code>string launchedAt = 5;</code>
     * @return The launchedAt.
     */
    java.lang.String getLaunchedAt();
    /**
     * <pre>
     * リリース
     * </pre>
     *
     * <code>string launchedAt = 5;</code>
     * @return The bytes for launchedAt.
     */
    com.google.protobuf.ByteString
        getLaunchedAtBytes();

    /**
     * <code>string createdAt = 6;</code>
     * @return The createdAt.
     */
    java.lang.String getCreatedAt();
    /**
     * <code>string createdAt = 6;</code>
     * @return The bytes for createdAt.
     */
    com.google.protobuf.ByteString
        getCreatedAtBytes();

    /**
     * <code>string updatedAt = 7;</code>
     * @return The updatedAt.
     */
    java.lang.String getUpdatedAt();
    /**
     * <code>string updatedAt = 7;</code>
     * @return The bytes for updatedAt.
     */
    com.google.protobuf.ByteString
        getUpdatedAtBytes();
  }
  /**
   * <pre>
   **
   * SNSスナップショット実績スキーマ
   * </pre>
   *
   * Protobuf type {@code SnsSnapshotAchievement}
   */
  public  static final class SnsSnapshotAchievement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SnsSnapshotAchievement)
      SnsSnapshotAchievementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SnsSnapshotAchievement.newBuilder() to construct.
    private SnsSnapshotAchievement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SnsSnapshotAchievement() {
      name_ = "";
      countryOfOrigin_ = "";
      launchedAt_ = "";
      createdAt_ = "";
      updatedAt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SnsSnapshotAchievement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SnsSnapshotAchievement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              countryOfOrigin_ = s;
              break;
            }
            case 24: {

              monthlyActiveUser_ = input.readInt64();
              break;
            }
            case 32: {

              arpu_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              launchedAt_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              createdAt_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              updatedAt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Base.internal_static_SnsSnapshotAchievement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Base.internal_static_SnsSnapshotAchievement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Base.SnsSnapshotAchievement.class, Base.SnsSnapshotAchievement.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYOFORIGIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object countryOfOrigin_;
    /**
     * <pre>
     * 発祥
     * </pre>
     *
     * <code>string countryOfOrigin = 2;</code>
     * @return The countryOfOrigin.
     */
    public java.lang.String getCountryOfOrigin() {
      java.lang.Object ref = countryOfOrigin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryOfOrigin_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 発祥
     * </pre>
     *
     * <code>string countryOfOrigin = 2;</code>
     * @return The bytes for countryOfOrigin.
     */
    public com.google.protobuf.ByteString
        getCountryOfOriginBytes() {
      java.lang.Object ref = countryOfOrigin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryOfOrigin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTHLYACTIVEUSER_FIELD_NUMBER = 3;
    private long monthlyActiveUser_;
    /**
     * <pre>
     * mau
     * </pre>
     *
     * <code>int64 monthlyActiveUser = 3;</code>
     * @return The monthlyActiveUser.
     */
    public long getMonthlyActiveUser() {
      return monthlyActiveUser_;
    }

    public static final int ARPU_FIELD_NUMBER = 4;
    private long arpu_;
    /**
     * <pre>
     * average revenue per user
     * </pre>
     *
     * <code>int64 arpu = 4;</code>
     * @return The arpu.
     */
    public long getArpu() {
      return arpu_;
    }

    public static final int LAUNCHEDAT_FIELD_NUMBER = 5;
    private volatile java.lang.Object launchedAt_;
    /**
     * <pre>
     * リリース
     * </pre>
     *
     * <code>string launchedAt = 5;</code>
     * @return The launchedAt.
     */
    public java.lang.String getLaunchedAt() {
      java.lang.Object ref = launchedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        launchedAt_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * リリース
     * </pre>
     *
     * <code>string launchedAt = 5;</code>
     * @return The bytes for launchedAt.
     */
    public com.google.protobuf.ByteString
        getLaunchedAtBytes() {
      java.lang.Object ref = launchedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        launchedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDAT_FIELD_NUMBER = 6;
    private volatile java.lang.Object createdAt_;
    /**
     * <code>string createdAt = 6;</code>
     * @return The createdAt.
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      }
    }
    /**
     * <code>string createdAt = 6;</code>
     * @return The bytes for createdAt.
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 7;
    private volatile java.lang.Object updatedAt_;
    /**
     * <code>string updatedAt = 7;</code>
     * @return The updatedAt.
     */
    public java.lang.String getUpdatedAt() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedAt_ = s;
        return s;
      }
    }
    /**
     * <code>string updatedAt = 7;</code>
     * @return The bytes for updatedAt.
     */
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getCountryOfOriginBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, countryOfOrigin_);
      }
      if (monthlyActiveUser_ != 0L) {
        output.writeInt64(3, monthlyActiveUser_);
      }
      if (arpu_ != 0L) {
        output.writeInt64(4, arpu_);
      }
      if (!getLaunchedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, launchedAt_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createdAt_);
      }
      if (!getUpdatedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, updatedAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getCountryOfOriginBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, countryOfOrigin_);
      }
      if (monthlyActiveUser_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, monthlyActiveUser_);
      }
      if (arpu_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, arpu_);
      }
      if (!getLaunchedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, launchedAt_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createdAt_);
      }
      if (!getUpdatedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, updatedAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Base.SnsSnapshotAchievement)) {
        return super.equals(obj);
      }
      Base.SnsSnapshotAchievement other = (Base.SnsSnapshotAchievement) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getCountryOfOrigin()
          .equals(other.getCountryOfOrigin())) return false;
      if (getMonthlyActiveUser()
          != other.getMonthlyActiveUser()) return false;
      if (getArpu()
          != other.getArpu()) return false;
      if (!getLaunchedAt()
          .equals(other.getLaunchedAt())) return false;
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COUNTRYOFORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getCountryOfOrigin().hashCode();
      hash = (37 * hash) + MONTHLYACTIVEUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMonthlyActiveUser());
      hash = (37 * hash) + ARPU_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getArpu());
      hash = (37 * hash) + LAUNCHEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getLaunchedAt().hashCode();
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Base.SnsSnapshotAchievement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base.SnsSnapshotAchievement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base.SnsSnapshotAchievement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Base.SnsSnapshotAchievement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Base.SnsSnapshotAchievement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Base.SnsSnapshotAchievement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Base.SnsSnapshotAchievement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * SNSスナップショット実績スキーマ
     * </pre>
     *
     * Protobuf type {@code SnsSnapshotAchievement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SnsSnapshotAchievement)
        Base.SnsSnapshotAchievementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Base.internal_static_SnsSnapshotAchievement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Base.internal_static_SnsSnapshotAchievement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Base.SnsSnapshotAchievement.class, Base.SnsSnapshotAchievement.Builder.class);
      }

      // Construct using Base.SnsSnapshotAchievement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        countryOfOrigin_ = "";

        monthlyActiveUser_ = 0L;

        arpu_ = 0L;

        launchedAt_ = "";

        createdAt_ = "";

        updatedAt_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Base.internal_static_SnsSnapshotAchievement_descriptor;
      }

      @java.lang.Override
      public Base.SnsSnapshotAchievement getDefaultInstanceForType() {
        return Base.SnsSnapshotAchievement.getDefaultInstance();
      }

      @java.lang.Override
      public Base.SnsSnapshotAchievement build() {
        Base.SnsSnapshotAchievement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Base.SnsSnapshotAchievement buildPartial() {
        Base.SnsSnapshotAchievement result = new Base.SnsSnapshotAchievement(this);
        result.name_ = name_;
        result.countryOfOrigin_ = countryOfOrigin_;
        result.monthlyActiveUser_ = monthlyActiveUser_;
        result.arpu_ = arpu_;
        result.launchedAt_ = launchedAt_;
        result.createdAt_ = createdAt_;
        result.updatedAt_ = updatedAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Base.SnsSnapshotAchievement) {
          return mergeFrom((Base.SnsSnapshotAchievement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Base.SnsSnapshotAchievement other) {
        if (other == Base.SnsSnapshotAchievement.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getCountryOfOrigin().isEmpty()) {
          countryOfOrigin_ = other.countryOfOrigin_;
          onChanged();
        }
        if (other.getMonthlyActiveUser() != 0L) {
          setMonthlyActiveUser(other.getMonthlyActiveUser());
        }
        if (other.getArpu() != 0L) {
          setArpu(other.getArpu());
        }
        if (!other.getLaunchedAt().isEmpty()) {
          launchedAt_ = other.launchedAt_;
          onChanged();
        }
        if (!other.getCreatedAt().isEmpty()) {
          createdAt_ = other.createdAt_;
          onChanged();
        }
        if (!other.getUpdatedAt().isEmpty()) {
          updatedAt_ = other.updatedAt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Base.SnsSnapshotAchievement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Base.SnsSnapshotAchievement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object countryOfOrigin_ = "";
      /**
       * <pre>
       * 発祥
       * </pre>
       *
       * <code>string countryOfOrigin = 2;</code>
       * @return The countryOfOrigin.
       */
      public java.lang.String getCountryOfOrigin() {
        java.lang.Object ref = countryOfOrigin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryOfOrigin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 発祥
       * </pre>
       *
       * <code>string countryOfOrigin = 2;</code>
       * @return The bytes for countryOfOrigin.
       */
      public com.google.protobuf.ByteString
          getCountryOfOriginBytes() {
        java.lang.Object ref = countryOfOrigin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryOfOrigin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 発祥
       * </pre>
       *
       * <code>string countryOfOrigin = 2;</code>
       * @param value The countryOfOrigin to set.
       * @return This builder for chaining.
       */
      public Builder setCountryOfOrigin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryOfOrigin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 発祥
       * </pre>
       *
       * <code>string countryOfOrigin = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryOfOrigin() {
        
        countryOfOrigin_ = getDefaultInstance().getCountryOfOrigin();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 発祥
       * </pre>
       *
       * <code>string countryOfOrigin = 2;</code>
       * @param value The bytes for countryOfOrigin to set.
       * @return This builder for chaining.
       */
      public Builder setCountryOfOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryOfOrigin_ = value;
        onChanged();
        return this;
      }

      private long monthlyActiveUser_ ;
      /**
       * <pre>
       * mau
       * </pre>
       *
       * <code>int64 monthlyActiveUser = 3;</code>
       * @return The monthlyActiveUser.
       */
      public long getMonthlyActiveUser() {
        return monthlyActiveUser_;
      }
      /**
       * <pre>
       * mau
       * </pre>
       *
       * <code>int64 monthlyActiveUser = 3;</code>
       * @param value The monthlyActiveUser to set.
       * @return This builder for chaining.
       */
      public Builder setMonthlyActiveUser(long value) {
        
        monthlyActiveUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * mau
       * </pre>
       *
       * <code>int64 monthlyActiveUser = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonthlyActiveUser() {
        
        monthlyActiveUser_ = 0L;
        onChanged();
        return this;
      }

      private long arpu_ ;
      /**
       * <pre>
       * average revenue per user
       * </pre>
       *
       * <code>int64 arpu = 4;</code>
       * @return The arpu.
       */
      public long getArpu() {
        return arpu_;
      }
      /**
       * <pre>
       * average revenue per user
       * </pre>
       *
       * <code>int64 arpu = 4;</code>
       * @param value The arpu to set.
       * @return This builder for chaining.
       */
      public Builder setArpu(long value) {
        
        arpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * average revenue per user
       * </pre>
       *
       * <code>int64 arpu = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearArpu() {
        
        arpu_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object launchedAt_ = "";
      /**
       * <pre>
       * リリース
       * </pre>
       *
       * <code>string launchedAt = 5;</code>
       * @return The launchedAt.
       */
      public java.lang.String getLaunchedAt() {
        java.lang.Object ref = launchedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          launchedAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * リリース
       * </pre>
       *
       * <code>string launchedAt = 5;</code>
       * @return The bytes for launchedAt.
       */
      public com.google.protobuf.ByteString
          getLaunchedAtBytes() {
        java.lang.Object ref = launchedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          launchedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * リリース
       * </pre>
       *
       * <code>string launchedAt = 5;</code>
       * @param value The launchedAt to set.
       * @return This builder for chaining.
       */
      public Builder setLaunchedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        launchedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * リリース
       * </pre>
       *
       * <code>string launchedAt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLaunchedAt() {
        
        launchedAt_ = getDefaultInstance().getLaunchedAt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * リリース
       * </pre>
       *
       * <code>string launchedAt = 5;</code>
       * @param value The bytes for launchedAt to set.
       * @return This builder for chaining.
       */
      public Builder setLaunchedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        launchedAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createdAt_ = "";
      /**
       * <code>string createdAt = 6;</code>
       * @return The createdAt.
       */
      public java.lang.String getCreatedAt() {
        java.lang.Object ref = createdAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createdAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createdAt = 6;</code>
       * @return The bytes for createdAt.
       */
      public com.google.protobuf.ByteString
          getCreatedAtBytes() {
        java.lang.Object ref = createdAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createdAt = 6;</code>
       * @param value The createdAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createdAt = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = getDefaultInstance().getCreatedAt();
        onChanged();
        return this;
      }
      /**
       * <code>string createdAt = 6;</code>
       * @param value The bytes for createdAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createdAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object updatedAt_ = "";
      /**
       * <code>string updatedAt = 7;</code>
       * @return The updatedAt.
       */
      public java.lang.String getUpdatedAt() {
        java.lang.Object ref = updatedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updatedAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string updatedAt = 7;</code>
       * @return The bytes for updatedAt.
       */
      public com.google.protobuf.ByteString
          getUpdatedAtBytes() {
        java.lang.Object ref = updatedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updatedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string updatedAt = 7;</code>
       * @param value The updatedAt to set.
       * @return This builder for chaining.
       */
      public Builder setUpdatedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string updatedAt = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = getDefaultInstance().getUpdatedAt();
        onChanged();
        return this;
      }
      /**
       * <code>string updatedAt = 7;</code>
       * @param value The bytes for updatedAt to set.
       * @return This builder for chaining.
       */
      public Builder setUpdatedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SnsSnapshotAchievement)
    }

    // @@protoc_insertion_point(class_scope:SnsSnapshotAchievement)
    private static final Base.SnsSnapshotAchievement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Base.SnsSnapshotAchievement();
    }

    public static Base.SnsSnapshotAchievement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SnsSnapshotAchievement>
        PARSER = new com.google.protobuf.AbstractParser<SnsSnapshotAchievement>() {
      @java.lang.Override
      public SnsSnapshotAchievement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnsSnapshotAchievement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SnsSnapshotAchievement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SnsSnapshotAchievement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Base.SnsSnapshotAchievement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnsSnapshotAchievement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SnsSnapshotAchievement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\032\037google/protobuf/timestamp." +
      "proto\"\242\001\n\026SnsSnapshotAchievement\022\014\n\004name" +
      "\030\001 \001(\t\022\027\n\017countryOfOrigin\030\002 \001(\t\022\031\n\021month" +
      "lyActiveUser\030\003 \001(\003\022\014\n\004arpu\030\004 \001(\003\022\022\n\nlaun" +
      "chedAt\030\005 \001(\t\022\021\n\tcreatedAt\030\006 \001(\t\022\021\n\tupdat" +
      "edAt\030\007 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_SnsSnapshotAchievement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SnsSnapshotAchievement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SnsSnapshotAchievement_descriptor,
        new java.lang.String[] { "Name", "CountryOfOrigin", "MonthlyActiveUser", "Arpu", "LaunchedAt", "CreatedAt", "UpdatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
